#include "app_events.hpp"

ESP_EVENT_DEFINE_BASE(LOCK_EVENT);
ESP_EVENT_DEFINE_BASE(NFC_EVENT);
ESP_EVENT_DEFINE_BASE(HK_EVENT);
ESP_EVENT_DEFINE_BASE(HW_EVENT);
ESP_EVENT_DEFINE_BASE(MQTT_EVENT);
ESP_EVENT_DEFINE_BASE(ETH_APP_EVENT);
ESP_EVENT_DEFINE_BASE(HOUSEHOLD_EVENT);
ESP_EVENT_DEFINE_BASE(NODE_EVENT);
ESP_EVENT_DEFINE_BASE(BACKUP_EVENT);
ESP_EVENT_DEFINE_BASE(AUDIT_EVENT);
ESP_EVENT_DEFINE_BASE(HEALTH_EVENT);
ESP_EVENT_DEFINE_BASE(PROVISION_EVENT);
ESP_EVENT_DEFINE_BASE(SECURITY_EVENT);
