#pragma once
#include "esp_event.h"

ESP_EVENT_DECLARE_BASE(LOCK_EVENT);
enum {
    LOCK_STATE_CHANGED,
    LOCK_UPDATE_STATE,
    LOCK_TARGET_STATE_CHANGED,
    LOCK_OVERRIDE_STATE,
};

ESP_EVENT_DECLARE_BASE(NFC_EVENT);
enum {
    NFC_TAP_EVENT,
    NFC_STATUS_CHANGED,
};

ESP_EVENT_DECLARE_BASE(HK_EVENT);
enum {
    HK_INTERNAL_EVENT,
};

ESP_EVENT_DECLARE_BASE(HW_EVENT);
enum {
    HW_ACTION,
    HW_ALT_ACTION,
    HW_CONFIG_CHANGED,
};

ESP_EVENT_DECLARE_BASE(MQTT_EVENT);
enum {
    MQTT_STATUS_CHANGED,
};

// ETH_EVENT is taken by esp_eth (esp_eth_com.h), hence the APP_ prefix.
ESP_EVENT_DECLARE_BASE(ETH_APP_EVENT);
enum {
    ETH_STARTED,
    ETH_GOT_IP,
    ETH_LOST_IP,
    ETH_DISCONNECTED,
    ETH_STOPPED,
};

ESP_EVENT_DECLARE_BASE(HOUSEHOLD_EVENT);
enum {
    HOUSEHOLD_STATE_CHANGED,
    HOUSEHOLD_MEMBERSHIP_CHANGED,
    HOUSEHOLD_PROVISIONING_STATE_CHANGED,
};

ESP_EVENT_DECLARE_BASE(NODE_EVENT);
enum {
    NODE_IDENTITY_CHANGED,
    NODE_STATE_CHANGED,
};

ESP_EVENT_DECLARE_BASE(BACKUP_EVENT);
enum {
    BACKUP_STARTED,
    BACKUP_COMPLETED,
    BACKUP_FAILED,
    BACKUP_INTEGRITY_ERROR,
    RESTORE_STARTED,
    RESTORE_COMPLETED,
    RESTORE_FAILED,
};

ESP_EVENT_DECLARE_BASE(AUDIT_EVENT);
enum {
    AUDIT_RECORDED,
};

ESP_EVENT_DECLARE_BASE(HEALTH_EVENT);
enum {
    HEALTH_UPDATED,
};

// Guest NFC tags: a locally verified credential written onto an ordinary
// ISO14443A card so guests can unlock without an Apple device. No HomeKey, no
// MQTT and no internet are involved in a tap -- only in teaching/distribution.
ESP_EVENT_DECLARE_BASE(GUEST_EVENT);
enum {
    GUEST_STATE_CHANGED,  ///< enable flag, default validity or the tag table changed
    GUEST_WRITE_RESULT,   ///< a teach attempt on a card finished (success or not)
};

ESP_EVENT_DECLARE_BASE(PROVISION_EVENT);
enum {
    PROVISION_CODE_ISSUED,
    PROVISION_COMPLETED,
    PROVISION_FAILED,
};

ESP_EVENT_DECLARE_BASE(SECURITY_EVENT);
enum {
    SECURITY_POSTURE_CHANGED,
};
