#!/bin/sh
# Build a firmware image for an ESP32-C3 on macOS/Homebrew hosts.
#
# WHY THIS EXISTS
#
# `idf.py set-target esp32c3` fails on a Homebrew CMake host with:
#
#     clang: error: unknown argument: '--traditional-format'
#     clang: error: unsupported argument 'rv32imafdc_zicsr_zifencei' to option '-march='
#
# That message is misleading. The RISC-V GCC driver is fine and is the one running;
# what fails is the ASSEMBLER step. IDF's `riscv32-esp-elf-as` is not binutils but a
# small Rust dispatcher that picks between `riscv32-esp-elf-as-xespv1/v2p1/v2p2`
# (the real GNU assembler). When it cannot resolve its target variant it exits
# non-zero, GCC's `-print-prog-name=as` reports the bare name `as`, and the OS then
# resolves that to `/usr/bin/as`, which is Apple clang. clang is handed RISC-V
# flags and rejects them.
#
# The fix is to put a directory on PATH containing an `as` that points straight at
# the real GNU assembler, bypassing the dispatcher entirely. `ld` is shimmed for
# the same reason.
#
# This is a HOST workaround and does not change the project. It is used instead of
# `idf.py set-target esp32c3` (the target switch itself is safe; the assembler
# resolution is what breaks).
#
# USAGE
#   ./scripts/build_esp32c3.sh set-target        # configure the build for esp32c3
#   ./scripts/build_esp32c3.sh build             # compile
#   ./scripts/build_esp32c3.sh flash [port]      # compile, then write to the board
#   ./scripts/build_esp32c3.sh monitor [port]    # serial monitor (quit with Ctrl+])
#
# flash refuses to run while the port is busy, because a monitor left attached races
# the write and can leave a non-booting image. Port defaults to the first
# /dev/cu.usbmodem* that exists.

set -eu

IDF_DIR="${IDF_PATH:-$HOME/esp/esp-idf}"
TOOLCHAIN_DIR="$HOME/.espressif/tools/riscv32-esp-elf"

if [ ! -d "$IDF_DIR" ]; then
  echo "error: ESP-IDF not found at $IDF_DIR (set IDF_PATH)" >&2
  exit 1
fi

# Newest installed RISC-V toolchain.
TC=""
for candidate in $(ls -d "$TOOLCHAIN_DIR"/*/ 2>/dev/null | sort -r); do
  if [ -x "${candidate}riscv32-esp-elf/bin/riscv32-esp-elf-gcc" ]; then
    TC="${candidate}riscv32-esp-elf/bin"
    break
  fi
done

if [ -z "$TC" ]; then
  echo "error: the RISC-V toolchain is not installed. Run:" >&2
  echo "  python \"\$IDF_PATH/tools/idf_tools.py\" --non-interactive install riscv32-esp-elf" >&2
  exit 1
fi

# The real GNU assembler and linker. The `-xespv2p2` build is the ISA variant this
# ESP32-C3 (rv32imc, no F/D, no xesp extension) needs; `as-xespv2p1` is an earlier
# ISA revision kept for older chips and is picked automatically by the dispatcher
# when it works.
AS_BIN="$TC/riscv32-esp-elf-as-xespv2p2"
LD_BIN="$TC/riscv32-esp-elf-ld"
if [ ! -x "$AS_BIN" ]; then
  echo "error: $AS_BIN not found - the toolchain install is incomplete" >&2
  exit 1
fi

# Shim directory. Recreated every run so a stale or wrong link cannot linger.
SHIM="${TMPDIR:-/tmp}/hk-riscv-shim"
rm -rf "$SHIM"
mkdir -p "$SHIM"
ln -s "$AS_BIN" "$SHIM/as"
[ -x "$LD_BIN" ] && ln -s "$LD_BIN" "$SHIM/ld"

echo "toolchain : $TC"
echo "assembler : $AS_BIN"
echo "shim      : $SHIM"
echo

# Put the shim first, then the toolchain, then let export.sh add the rest.
export PATH="$SHIM:$TC:$PATH"

if [ ! -f "$IDF_DIR/export.sh" ]; then
  echo "error: $IDF_DIR/export.sh not found" >&2
  exit 1
fi
# shellcheck disable=SC1091
. "$IDF_DIR/export.sh" >/dev/null

export PATH="$SHIM:$TC:$PATH"
export CI=true
export CMAKE_POLICY_VERSION_MINIMUM=3.5

# This is the line that makes the target switch actually stick.
#
# sdkconfig is generated by confgen, which picks the target from the IDF_TARGET
# ENVIRONMENT variable - not from the target argument given to `set-target`. That
# argument only reaches CMake, which records it in build/CMakeCache.txt.
#
# So with IDF_TARGET unset here, the two disagree: CMakeCache says esp32c3 while the
# freshly generated sdkconfig falls back to Kconfig's default of esp32. The build then
# dies with:
#   Target 'esp32' in sdkconfig '.../sdkconfig' does not match currently selected
#   IDF_TARGET 'esp32c3'
# and worse, anything reading sdkconfig (or a stale flash_args) sees the wrong chip.
# Exporting it keeps sdkconfig, CMakeCache and the compiler all on the same target.
export IDF_TARGET=esp32c3

ACTION="${1:-build}"

# Force the build directory and sdkconfig onto esp32c3.
#
# Both have to be dealt with, and for different reasons:
#
#  * `rm -rf build` alone is not enough. `idf.py set-target` applies the requested
#    target through build/CMakeCache and a generated sdkconfig only when there is no
#    sdkconfig to prefer. This tree keeps a checked-in sdkconfig at the repo root (a
#    classic-ESP32 one), and IDF reads that in preference to the target argument. So a
#    plain `rm -rf build && idf.py set-target esp32c3` silently builds for esp32 while
#    build/flash_args keeps the C3 offsets from the generate step - two files in the
#    same directory describing different chips. The offset lookup reads flash_args, so
#    that combination writes an esp32 bootloader to 0x0, which is where a C3 one goes
#    and where an esp32 one does not.
#  * The old sdkconfig is moved aside rather than deleted, so the configured values
#    stay recoverable.
do_set_target() {
  rm -rf build
  if [ -f sdkconfig ]; then
    backup="sdkconfig.esp32.bak"
    mv sdkconfig "$backup"
    echo "existing sdkconfig moved to $backup so the target switch can take effect"
  fi
  idf.py set-target esp32c3
}

# The target recorded in sdkconfig, or empty when the file does not exist.
sdkconfig_target() {
  [ -f sdkconfig ] || return 0
  sed -n 's/^CONFIG_IDF_TARGET="\(.*\)"$/\1/p' sdkconfig | head -1
}

ACTION="${1:-build}"
PORT="${2:-}"

if [ -z "$PORT" ]; then
  for p in /dev/cu.usbmodem*; do
    [ -e "$p" ] && PORT="$p" && break
  done
fi

# PID holding the serial port, or empty. Flashing while another process (usually an
# `idf.py monitor` left running) owns the port races the write and can leave an image
# that does not boot; the failure mode is a boot loop that only `erase_flash` clears.
port_holder() {
  [ -n "$1" ] || return 0
  command -v lsof >/dev/null 2>&1 || return 0
  lsof -t "$1" 2>/dev/null | head -1
}

# Configure/build if needed. Shared by build/flash so both self-heal identically.
ensure_built() {
  # A build interrupted part way (SIGINT during ninja) can leave sdkconfig back at
  # Kconfig's default of esp32 while build/ still targets esp32c3. Every subsequent
  # `idf.py build` then fails with:
  #
  #   Project sdkconfig '...' was generated for target 'esp32', but environment
  #   variable IDF_TARGET is set to 'esp32c3'.
  #
  # Only set-target rewrites sdkconfig, so run it when the two disagree; otherwise a
  # plain reconfigure is enough and preserves the incremental build.
  cfg_target=$(sdkconfig_target)
  if [ "$cfg_target" != "esp32c3" ]; then
    echo "sdkconfig target is '${cfg_target:-none}', expected esp32c3 - reconfiguring"
    do_set_target || exit 1
    echo
  else
    # reconfigure so the target switch is picked up even after a failed attempt
    idf.py reconfigure || exit 1
  fi
  idf.py build
}

case "$ACTION" in
  set-target)
    do_set_target
    exit $?
    ;;
  build|"")
    ensure_built
    exit $?
    ;;
  flash)
    [ -n "$PORT" ] || { echo "error: no serial port found; pass one" >&2; exit 1; }
    holder=$(port_holder "$PORT")
    if [ -n "$holder" ]; then
      echo "error: $PORT is in use by pid $holder." >&2
      echo "Quit `idf.py monitor` (Ctrl+]) before flashing, or the write will race it" >&2
      echo "and can leave a non-booting image." >&2
      exit 1
    fi
    ensure_built || exit 1
    exec idf.py -p "$PORT" flash
    ;;
  monitor)
    [ -n "$PORT" ] || { echo "error: no serial port found; pass one" >&2; exit 1; }
    exec idf.py -p "$PORT" monitor
    ;;
  *)
    echo "usage: $0 [set-target|build|flash|monitor] [port]" >&2
    exit 2
    ;;
esac
