"""Post-build hook: flash the ESP-IDF generated littlefs image with PlatformIO.

`main/CMakeLists.txt` creates the littlefs image of the ``spiffs`` partition via

    littlefs_create_partition_image(spiffs ../data/dist FLASH_IN_PROJECT)

which ``idf.py flash`` uploads automatically alongside the application. PlatformIO
only flashes the bootloader, the partition table, the otadata image and the app,
so this hook appends the image produced by the ESP-IDF build
(``$BUILD_DIR/spiffs.bin``) to the esptool command line at the offset taken from
``board_build.partitions``.

Result: ``pio run -t upload`` flashes the complete firmware including the web UI.
"""

import os

Import("env")  # noqa: F821  (injected by PlatformIO/SCons)

try:  # SCons globals, only available while a target is being built
    from SCons.Script import COMMAND_LINE_TARGETS
except ImportError:  # pragma: no cover
    COMMAND_LINE_TARGETS = []

BUILD_DIR = env.subst("$BUILD_DIR")  # noqa: F821
PARTITION_NAME = "spiffs"
PARTITION_IMAGE = os.path.join(BUILD_DIR, "%s.bin" % PARTITION_NAME)


def _parse_size(value):
    value = value.strip().upper()
    if value.endswith("K"):
        return int(value[:-1], 0) * 1024
    if value.endswith("M"):
        return int(value[:-1], 0) * 1024 * 1024
    return int(value, 0)


def find_partition_offset(csv_path, name):
    """Return the offset of ``name`` in a partition CSV.

    Empty offsets are resolved exactly like ESP-IDF's `gen_esp32part.py` and
    PlatformIO's own parser: partitions follow each other, app partitions are
    aligned to 64 kB and the table itself starts at 0x9000.
    """
    next_offset = 0x9000
    with open(csv_path) as fp:
        for line in fp:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            tokens = [t.strip() for t in line.split(",")]
            if len(tokens) < 5:
                continue
            bound = 0x10000 if tokens[1] in ("0", "app") else 4
            offset = (
                _parse_size(tokens[3])
                if tokens[3]
                else (next_offset + bound - 1) & ~(bound - 1)
            )
            if tokens[0] == name:
                return offset
            next_offset = offset + _parse_size(tokens[4])
    return None


def _add_filesystem_image():
    if env.subst("$UPLOAD_PROTOCOL") != "esptool":  # noqa: F821
        return
    if {"uploadfs", "uploadfsota"} & set(COMMAND_LINE_TARGETS):
        return  # -t uploadfs already writes the filesystem image
    if not os.path.isfile(PARTITION_IMAGE):
        print(
            "Warning: '%s' was not generated by the ESP-IDF build, "
            "the web UI will not be updated." % PARTITION_IMAGE
        )
        return

    csv_path = env.subst("$PARTITIONS_TABLE_CSV")  # noqa: F821
    if not csv_path or not os.path.isfile(csv_path):
        print("Warning: partition table '%s' not found." % csv_path)
        return

    offset = find_partition_offset(csv_path, PARTITION_NAME)
    if offset is None:
        print(
            "Warning: no '%s' partition in '%s'." % (PARTITION_NAME, csv_path)
        )
        return

    print("Adding littlefs image %s to the upload at %s" % (PARTITION_IMAGE, hex(offset)))
    env.Append(UPLOADERFLAGS=[hex(offset), PARTITION_IMAGE])  # noqa: F821


_add_filesystem_image()
