"""Post-build hook: build and flash the littlefs web UI image.

`main/CMakeLists.txt` creates the littlefs image of the ``spiffs`` partition via

    littlefs_create_partition_image(spiffs ../data/dist FLASH_IN_PROJECT)

which ``idf.py flash`` uploads automatically alongside the application. PlatformIO
compiles the project with SCons and never runs ESP-IDF's ninja targets, so this
hook

1. runs just the ESP-IDF target ``littlefs_spiffs_bin`` (littlefs-python, the same
   tool and configuration an idf.py build uses) to produce ``$BUILD_DIR/spiffs.bin``,
2. appends that image to the esptool command line at the offset of the ``spiffs``
   partition, taken from ``board_build.partitions``.

PlatformIO itself only flashes the bootloader, the partition table, the otadata
image and the application. Result: ``pio run -t upload`` flashes everything,
including the web UI.
"""

import os
import subprocess

Import("env")  # noqa: F821  (injected by PlatformIO/SCons)

try:  # SCons globals, only available while a target is being built
    from SCons.Script import COMMAND_LINE_TARGETS
except ImportError:  # pragma: no cover
    COMMAND_LINE_TARGETS = []

BUILD_DIR = env.subst("$BUILD_DIR")  # noqa: F821
PARTITION_NAME = "spiffs"
PARTITION_IMAGE = os.path.join(BUILD_DIR, "%s.bin" % PARTITION_NAME)
IMAGE_TARGET = "littlefs_%s_bin" % PARTITION_NAME  # main/CMakeLists.txt uses littlefs


def _parse_size(value):
    value = value.strip().upper()
    if value.endswith("K"):
        return int(value[:-1], 0) * 1024
    if value.endswith("M"):
        return int(value[:-1], 0) * 1024 * 1024
    return int(value, 0)


def find_partition_offset(csv_path, name):
    """Return the offset of ``name`` in a partition CSV.

    Empty offsets are resolved exactly like ESP-IDF's `gen_esp32part.py` and
    PlatformIO's own parser: partitions follow each other, app partitions are
    aligned to 64 kB and the table itself starts at 0x9000.
    """
    next_offset = 0x9000
    with open(csv_path) as fp:
        for line in fp:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            tokens = [t.strip() for t in line.split(",")]
            if len(tokens) < 5:
                continue
            bound = 0x10000 if tokens[1] in ("0", "app") else 4
            offset = (
                _parse_size(tokens[3])
                if tokens[3]
                else (next_offset + bound - 1) & ~(bound - 1)
            )
            if tokens[0] == name:
                return offset
            next_offset = offset + _parse_size(tokens[4])
    return None


def _idf_build_env():
    """Environment ESP-IDF's CMake/ninja expects (IDF_PATH + toolchain on PATH)."""
    platform = env.PioPlatform()  # noqa: F821
    paths = []
    for package, subdir in (
        ("toolchain-xtensa-esp-elf", "bin"),
        ("tool-ninja", ""),
        ("tool-cmake", "bin"),
    ):
        package_dir = platform.get_package_dir(package)
        if package_dir:
            paths.append(os.path.join(package_dir, subdir))
    python_exe = env.subst("$PYTHONEXE")  # noqa: F821
    if python_exe:
        paths.append(os.path.dirname(python_exe))

    build_env = os.environ.copy()
    build_env["IDF_PATH"] = platform.get_package_dir("framework-espidf")
    rom_elfs = platform.get_package_dir("tool-esp-rom-elfs")
    if rom_elfs:
        build_env["ESP_ROM_ELF_DIR"] = rom_elfs
    build_env["PATH"] = os.pathsep.join(
        [p for p in paths if p] + [build_env.get("PATH", "")]
    )
    return build_env


def _build_web_ui_image():
    """Produce $BUILD_DIR/spiffs.bin with ESP-IDF's own image builder.

    PlatformIO's SCons build never executes ESP-IDF's ninja targets, so the image
    that main/CMakeLists.txt asked for does not exist yet. Running only the
    `littlefs_spiffs_bin` target (which creates littlefs_py_venv on first use and
    then runs littlefs-python) yields exactly what an idf.py build would produce.
    """
    build_dir = env.subst("$BUILD_DIR")  # noqa: F821
    ninja = os.path.join(
        env.PioPlatform().get_package_dir("tool-ninja") or "", "ninja"
    )  # noqa: F821
    if not os.path.isfile(ninja) or not os.path.isfile(
        os.path.join(build_dir, "build.ninja")
    ):
        return

    print("Building the littlefs web UI image (ESP-IDF: %s) ..." % IMAGE_TARGET)
    subprocess.check_call(
        [ninja, "-C", build_dir, IMAGE_TARGET], env=_idf_build_env()
    )


def _add_filesystem_image():
    if env.subst("$UPLOAD_PROTOCOL") != "esptool":  # noqa: F821
        return
    if {"uploadfs", "uploadfsota"} & set(COMMAND_LINE_TARGETS):
        return  # -t uploadfs already writes the filesystem image

    _build_web_ui_image()

    if not os.path.isfile(PARTITION_IMAGE):
        print(
            "Warning: '%s' was not generated by the ESP-IDF build, "
            "the web UI will not be updated." % PARTITION_IMAGE
        )
        return

    csv_path = env.subst("$PARTITIONS_TABLE_CSV")  # noqa: F821
    if not csv_path or not os.path.isfile(csv_path):
        print("Warning: partition table '%s' not found." % csv_path)
        return

    offset = find_partition_offset(csv_path, PARTITION_NAME)
    if offset is None:
        print(
            "Warning: no '%s' partition in '%s'." % (PARTITION_NAME, csv_path)
        )
        return

    print("Adding littlefs web UI image to the upload at %s" % hex(offset))
    env.Append(UPLOADERFLAGS=[hex(offset), PARTITION_IMAGE])  # noqa: F821


_add_filesystem_image()
